# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pokemon_pb2 as pokemon__pb2


class serverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.trainerCheck = channel.unary_unary(
                '/serverService/trainerCheck',
                request_serializer=pokemon__pb2.Position.SerializeToString,
                response_deserializer=pokemon__pb2.Spaces.FromString,
                )
        self.pokemonCheck = channel.unary_unary(
                '/serverService/pokemonCheck',
                request_serializer=pokemon__pb2.Position.SerializeToString,
                response_deserializer=pokemon__pb2.Spaces.FromString,
                )
        self.captured = channel.unary_unary(
                '/serverService/captured',
                request_serializer=pokemon__pb2.Position.SerializeToString,
                response_deserializer=pokemon__pb2.cFlag.FromString,
                )
        self.reportMove = channel.unary_unary(
                '/serverService/reportMove',
                request_serializer=pokemon__pb2.Position.SerializeToString,
                response_deserializer=pokemon__pb2.Valid.FromString,
                )


class serverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def trainerCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pokemonCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def captured(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reportMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'trainerCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.trainerCheck,
                    request_deserializer=pokemon__pb2.Position.FromString,
                    response_serializer=pokemon__pb2.Spaces.SerializeToString,
            ),
            'pokemonCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.pokemonCheck,
                    request_deserializer=pokemon__pb2.Position.FromString,
                    response_serializer=pokemon__pb2.Spaces.SerializeToString,
            ),
            'captured': grpc.unary_unary_rpc_method_handler(
                    servicer.captured,
                    request_deserializer=pokemon__pb2.Position.FromString,
                    response_serializer=pokemon__pb2.cFlag.SerializeToString,
            ),
            'reportMove': grpc.unary_unary_rpc_method_handler(
                    servicer.reportMove,
                    request_deserializer=pokemon__pb2.Position.FromString,
                    response_serializer=pokemon__pb2.Valid.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class serverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def trainerCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serverService/trainerCheck',
            pokemon__pb2.Position.SerializeToString,
            pokemon__pb2.Spaces.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pokemonCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serverService/pokemonCheck',
            pokemon__pb2.Position.SerializeToString,
            pokemon__pb2.Spaces.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def captured(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serverService/captured',
            pokemon__pb2.Position.SerializeToString,
            pokemon__pb2.cFlag.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reportMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serverService/reportMove',
            pokemon__pb2.Position.SerializeToString,
            pokemon__pb2.Valid.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
