# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pokemon.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rpokemon.proto\"\x15\n\x05\x63\x46lag\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\"$\n\x08Position\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\"!\n\x05Space\x12\x18\n\x05space\x18\x01 \x01(\x0b\x32\t.Position\" \n\x06Spaces\x12\x16\n\x06spaces\x18\x01 \x03(\x0b\x32\x06.Space\"\x16\n\x05Valid\x12\r\n\x05\x66lag1\x18\x01 \x01(\x08\x32\x97\x01\n\rserverService\x12\"\n\x0ctrainerCheck\x12\t.Position\x1a\x07.Spaces\x12\"\n\x0cpokemonCheck\x12\t.Position\x1a\x07.Spaces\x12\x1d\n\x08\x63\x61ptured\x12\t.Position\x1a\x06.cFlag\x12\x1f\n\nreportMove\x12\t.Position\x1a\x06.Validb\x06proto3')
)




_CFLAG = _descriptor.Descriptor(
  name='cFlag',
  full_name='cFlag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='cFlag.flag', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=38,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='Position.row', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='col', full_name='Position.col', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=76,
)


_SPACE = _descriptor.Descriptor(
  name='Space',
  full_name='Space',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='space', full_name='Space.space', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=111,
)


_SPACES = _descriptor.Descriptor(
  name='Spaces',
  full_name='Spaces',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spaces', full_name='Spaces.spaces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=145,
)


_VALID = _descriptor.Descriptor(
  name='Valid',
  full_name='Valid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag1', full_name='Valid.flag1', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=169,
)

_SPACE.fields_by_name['space'].message_type = _POSITION
_SPACES.fields_by_name['spaces'].message_type = _SPACE
DESCRIPTOR.message_types_by_name['cFlag'] = _CFLAG
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Space'] = _SPACE
DESCRIPTOR.message_types_by_name['Spaces'] = _SPACES
DESCRIPTOR.message_types_by_name['Valid'] = _VALID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

cFlag = _reflection.GeneratedProtocolMessageType('cFlag', (_message.Message,), dict(
  DESCRIPTOR = _CFLAG,
  __module__ = 'pokemon_pb2'
  # @@protoc_insertion_point(class_scope:cFlag)
  ))
_sym_db.RegisterMessage(cFlag)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'pokemon_pb2'
  # @@protoc_insertion_point(class_scope:Position)
  ))
_sym_db.RegisterMessage(Position)

Space = _reflection.GeneratedProtocolMessageType('Space', (_message.Message,), dict(
  DESCRIPTOR = _SPACE,
  __module__ = 'pokemon_pb2'
  # @@protoc_insertion_point(class_scope:Space)
  ))
_sym_db.RegisterMessage(Space)

Spaces = _reflection.GeneratedProtocolMessageType('Spaces', (_message.Message,), dict(
  DESCRIPTOR = _SPACES,
  __module__ = 'pokemon_pb2'
  # @@protoc_insertion_point(class_scope:Spaces)
  ))
_sym_db.RegisterMessage(Spaces)

Valid = _reflection.GeneratedProtocolMessageType('Valid', (_message.Message,), dict(
  DESCRIPTOR = _VALID,
  __module__ = 'pokemon_pb2'
  # @@protoc_insertion_point(class_scope:Valid)
  ))
_sym_db.RegisterMessage(Valid)



_SERVERSERVICE = _descriptor.ServiceDescriptor(
  name='serverService',
  full_name='serverService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=172,
  serialized_end=323,
  methods=[
  _descriptor.MethodDescriptor(
    name='trainerCheck',
    full_name='serverService.trainerCheck',
    index=0,
    containing_service=None,
    input_type=_POSITION,
    output_type=_SPACES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pokemonCheck',
    full_name='serverService.pokemonCheck',
    index=1,
    containing_service=None,
    input_type=_POSITION,
    output_type=_SPACES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='captured',
    full_name='serverService.captured',
    index=2,
    containing_service=None,
    input_type=_POSITION,
    output_type=_CFLAG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reportMove',
    full_name='serverService.reportMove',
    index=3,
    containing_service=None,
    input_type=_POSITION,
    output_type=_VALID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERSERVICE)

DESCRIPTOR.services_by_name['serverService'] = _SERVERSERVICE

# @@protoc_insertion_point(module_scope)
