# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpokemon.proto\"\x15\n\x05\x63\x46lag\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\"$\n\x08Position\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\"!\n\x05Space\x12\x18\n\x05space\x18\x01 \x01(\x0b\x32\t.Position\" \n\x06Spaces\x12\x16\n\x06spaces\x18\x01 \x03(\x0b\x32\x06.Space\"\x16\n\x05Valid\x12\r\n\x05\x66lag1\x18\x01 \x01(\x08\x32\x97\x01\n\rserverService\x12\"\n\x0ctrainerCheck\x12\t.Position\x1a\x07.Spaces\x12\"\n\x0cpokemonCheck\x12\t.Position\x1a\x07.Spaces\x12\x1d\n\x08\x63\x61ptured\x12\t.Position\x1a\x06.cFlag\x12\x1f\n\nreportMove\x12\t.Position\x1a\x06.Validb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pokemon_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFLAG._serialized_start=17
  _CFLAG._serialized_end=38
  _POSITION._serialized_start=40
  _POSITION._serialized_end=76
  _SPACE._serialized_start=78
  _SPACE._serialized_end=111
  _SPACES._serialized_start=113
  _SPACES._serialized_end=145
  _VALID._serialized_start=147
  _VALID._serialized_end=169
  _SERVERSERVICE._serialized_start=172
  _SERVERSERVICE._serialized_end=323
# @@protoc_insertion_point(module_scope)
